# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-07-05 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0002_auto_20200705_0431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='event',
        ),
        migrations.RemoveField(
            model_name='repo',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RestAPI.Actor'),
        ),
        migrations.AddField(
            model_name='event',
            name='repo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RestAPI.Repo'),
        ),
    ]
